---
- name: Install graylog repo
  apt:
    deb: https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}-repository_latest.deb
    state: "present"

- name: Install graylog server
  package:
    name: ['graylog-server', 'graylog-enterprise-plugins', 'graylog-integrations-plugins', 'graylog-enterprise-integrations-plugins']
    state: present
    update_cache: yes

- name: Stat GeoIP database
  stat:
    path: '/etc/graylog/server/GeoLite2-City.mmdb'
  register: geoip_stat

- name: Download and extract GeoIP database
  unarchive:
    src: '{{ geoip_url }}'
    dest: '/etc/graylog/server/'
    remote_src: yes
  when: not geoip_stat.stat.exists

#- name: Configure graylog defaults.
#  template:
#    src: graylog-server.j2
#    dest: /etc/default/graylog-server
#    owner: root
#    group: root
#    mode: 0644

#- name: Set admin password
#  lineinfile:
#    path: /etc/graylog/server/server.conf
#    regexp: '^root_password_sha2 ='
#    line: "root_password_sha2 = {{ graylog_root_password_sha2 }}"
    
#- name: Set secret key
#  shell: sed -i -e "s/password_secret =.*/password_secret = {{ graylog_password_secret }}/" /etc/graylog/server/server.conf      
#  notify:
#    - "reload systemd configuration"
#    - "restart graylog-server"

- name: Enable Graylog.
  service:
    name: graylog-server
    state: started
    enabled: yes

- meta: flush_handlers

- name: "Wait for Graylog server to startup"
  uri:
    url: "http://{{ graylog_http_bind_address }}:{{ graylog_port }}"
    status_code: 200
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
