---
- name: Install prerequisites 
  apt:
    name:
      - apt-transport-https
      - openjdk-8-jre-headless
      - uuid-runtime
      - pwgen
      - gnupg     
    state: present
    update_cache: yes
