---
- name: Install graylog repo
  apt:
    deb: https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}-repository_latest.deb
    state: "present"

- name: Install graylog server
  package:
    name: ['graylog-server', 'graylog-enterprise-plugins', 'graylog-integrations-plugins', 'graylog-enterprise-integrations-plugins']
    state: present
    update_cache: yes

- name: Stat GeoIP database
  stat:
    path: '/etc/graylog/server/GeoLite2-City.mmdb'
  register: geoip_stat

- name: Download and extract GeoIP database
  unarchive:
    src: '{{ geoip_url }}'
    dest: '/etc/graylog/server/'
    remote_src: yes
  when: not geoip_stat.stat.exists

#- name: Configure graylog defaults.
#  template:
#    src: graylog-server.j2
#    dest: /etc/default/graylog-server
#    owner: root
#    group: root
#    mode: 0644

- name: Set secret key
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^password_secret ='
    line: "password_secret = {{ graylog_password_secret }}"

- name: Set admin user
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^#root_username ='
    line: "root_password_sha2 = {{ graylog_root_username }}"

- name: Set admin password
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^root_password_sha2 ='
    line: "root_password_sha2 = {{ graylog_root_password_sha2 }}"

- name: Set graylog timezone
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^#root_timezone ='
    line: "root_timezone = {{ graylog_root_timezone }}"

- name: Set http publish uri
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^#http_publish_uri ='
    line: "http_publish_uri = http://{{ ansible_default_ipv4.address }}:{{ graylog_bind_port }}/"

- name: Set http bind address
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^#http_bind_address = 127.0.0.1:9000'
    line: "http_bind_address = {{ ansible_default_ipv4.address }}:{{ graylog_bind_port }}"
  notify:
    - "reload systemd configuration"
    - "restart graylog-server"

- meta: flush_handlers

- name: "Wait for Graylog server to startup"
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:{{ graylog_bind_port }}"
    status_code: 200
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
