---
- name: Add Mongodb GPG key
  apt_key:
    url: "{{ MONGODB_GPG_URL }}"
    state: present

- name: Add mongodb repository.
  apt_repository:
    repo: '{{ MONGODB_REPO_URL }}'
    state: present
    update_cache: yes

- name: "Install mongodb"
  apt:
    name: "mongodb-org={{ MONGODB_VERSION }}"
    state: "present"
    allow_unauthenticated: yes
  notify:
    - "reload systemd configuration"
    - "restart mongod"

- meta: "flush_handlers"

- name: "Wait for mongodb to startup"
  wait_for:
    host: "127.0.0.1"
    port: 27017
    delay: 5
    connect_timeout: 1
