---
# tasks file for wireguard_role

- name: Install prequisites on the server
  include: 'install_prerequisites.yml'
  tags: prerequisites

- name: Install mongodb
  include: 'install_mongodb.yml'
  tags: mongodb

- name: Install and configure elasticsearch
  include: 'install_elasticsearch.yml'
  tags: elasticsearch

- name: Install and configure graylog
  include: 'install_graylog.yml'
  tags: graylog
